In [1]:
from selenium import webdriver
from time import sleep
from selenium.webdriver.chrome.options import Options

options = Options()
options.add_argument('--headless')

browser = webdriver.Chrome(options=options)
url = 'https://u.muroran-it.ac.jp/kyomu/syllabustop2021/26_.html'
browser.get(url)

In [2]:
units = []
path_front = '/html/body/table[2]/tbody/tr['
count = 1
path_end = ']/td[5]/a'

for i in range(87):
    path = path_front + str(count) + path_end
    browser.find_element_by_xpath(path).click()
    unit = browser.find_element_by_xpath('//*[@id="tabs-1"]/table/tbody/tr[10]/td').text
    units.append(unit)
    browser.back()
    count += 1
    sleep(0.5)
    
unit

C:\Users\user\AppData\Local\Temp/ipykernel_21448/1906077650.py:8: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath(path).click()
C:\Users\user\AppData\Local\Temp/ipykernel_21448/1906077650.py:9: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  unit = browser.find_element_by_xpath('//*[@id="tabs-1"]/table/tbody/tr[10]/td').text

'2.0'

In [3]:
units2 = []
for item in units:
    
    #文字列の置換
    item_mod = item.replace(" ", "")
    
    #リストに追加
    units2.append(item_mod)
    
units2

['2.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '1.0',
 '1.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '1.0',
 '1.0',
 '1.0',
 '1.0',
 '1.0',
 '1.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '1.0',
 '2.0',
 '1.0',
 '1.0',
 '1.0',
 '1.0',
 '1.0',
 '2.0',
 '2.0',
 '1.0',
 '1.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '1.0',
 '2.0',
 '1.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '1.0',
 '2.0',
 '2.0',
 '2.0',
 '1.0',
 '1.0',
 '2.0',
 '1.0',
 '1.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '1.0',
 '1.0',
 '1.0',
 '1.0',
 '1.0',
 '1.0',
 '1.0',
 '2.0',
 '2.0']

In [4]:
codes = []
code_front = '/html/body/table[2]/tbody/tr['
count = 1
code_end = ']/td[6]'

for i in range(87):
    path = code_front + str(count) + code_end
    code = browser.find_element_by_xpath(path).text
    codes.append(code)
    count += 1
    sleep(0.5)
    
codes

C:\Users\user\AppData\Local\Temp/ipykernel_21448/1894764621.py:8: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  code = browser.find_element_by_xpath(path).text

['J4016',
 'J2055',
 'J2056',
 'J2078',
 'J4021',
 'J4022',
 'J4023',
 'J2062',
 'J4008',
 'J2057',
 'J4011',
 'J4012',
 'J2049',
 'J2076',
 'J4018',
 'J4019',
 'J2051',
 'J2095',
 'J4043',
 'J4036',
 'J4037',
 'J4038',
 'J2050',
 'J4024',
 'J4025',
 'J4026',
 'J4027',
 'J4028',
 'J4029',
 'J2094',
 'J4003',
 'J4004',
 'J4005',
 'J4033',
 'J4035',
 'J4013',
 'J4034',
 'J2072',
 'J2073',
 'J2074',
 'J2075',
 'J4046',
 'J4020',
 'J2093',
 'J4045',
 'J2099B',
 'J4044',
 'J2063',
 'J4006',
 'J4007',
 'J4014',
 'J2096',
 'J2097',
 'J2098',
 'J2061',
 'J4042',
 'J2058',
 'J4002',
 'J2052',
 'J4155',
 'J2053',
 'J2060',
 'J4156',
 'J2054',
 'J4040',
 'J4157',
 'J2059',
 'J4030',
 'J4001',
 'J4039',
 'J4032',
 'J4009',
 'J4010',
 'J2070',
 'J2071',
 'J2079',
 'J2081',
 'J4031',
 'J2064',
 'J2065',
 'J2066',
 'J2067',
 'J2068',
 'J2069',
 'J4041',
 'J2084',
 'J2082']

In [5]:
import pandas as pd

In [6]:
df = pd.DataFrame()

In [7]:
df['単位数'] = units2
df['時間割コード'] = codes

df

    単位数 時間割コード
0   2.0  J4016
1   2.0  J2055
2   2.0  J2056
3   2.0  J2078
4   2.0  J4021
..  ...    ...
82  1.0  J2068
83  1.0  J2069
84  1.0  J4041
85  2.0  J2084
86  2.0  J2082

[87 rows x 2 columns]

In [8]:
df.to_csv('学部・学科共通科目.csv',index=False)

In [9]:
browser.close()